### ISSUE TITLE
Request: HZCU 联合开发的请求

### ISSUE THREAD

**Issue by BaoZhuhan** [PeiPei233/zju-learning-assistant#12]
您好，我是来自浙大城市学院（HangZhou City Unv）的开发者。

HZCU 的课程系统”学在城院”与浙大高度相似，我想将本项目经过修改后开发出城院的衍生版本。

我们承诺：
1. 衍生版本将开源，且保持与源项目相同的 LICENSE
2. 衍生版本的新特性会提交一个 PR 回馈源项目
3. 衍生版本会标注代码来源，凡是在zju-learning-assistant贡献的作者也可以提交一个空的PR到衍生项目，成为衍生项目的作者。

希望得到您的允许。

**Comment by PeiPei233** [comment]
当然可以 欢迎欢迎👏
