### ISSUE TITLE
Appimage & deb 版本无法启动

### ISSUE THREAD

**Issue by Visytudz** [PeiPei233/zju-learning-assistant#14]
ubuntu22.04
之前用的appimage一切正常，最近打不开了，启动后显示一片白色（或黑色，见下图），重装appimage，或换成deb安装也是一样的问题。
![image](https://github.com/user-attachments/assets/4c4294c2-de97-419b-9a5d-1c296ad29845)

**Comment by PeiPei233** [comment]
是更新到新的了吗？试一下旧版可以不
