### ISSUE TITLE
智云课堂获取问题

### ISSUE THREAD

**Issue by STDquantum** [PeiPei233/zju-learning-assistant#3]
![image](https://github.com/PeiPei233/zju-learning-assistant/assets/60764289/099a15b8-3d03-41b2-80c0-6916482f2a6f)
点刷新就这样了

**Comment by PeiPei233** [comment]
请关闭系统代理，重开一下软件

**Comment by PeiPei233** [comment]
已在最新版本中修复 [Release v0.3.1](https://github.com/PeiPei233/zju-learning-assistant/releases/tag/v0.3.1)
