### ISSUE TITLE
mac拖入Application之后点开，显示“已损坏， 无法打开。你应该将它移到废纸篓”

### ISSUE THREAD

**Issue by chkhu** [PeiPei233/zju-learning-assistant#4]
首先给佬膜一个！

装的时候碰到一个问题如下
<img width="953" alt="image" src="https://github.com/PeiPei233/zju-learning-assistant/assets/109655311/8d3416c8-755f-453a-85e0-ddacf9ee05e7">

信息：
Release的来源是v0.3.2: zju-learning-assistant_0.3.2_aarch64.dmg
https://github.com/PeiPei233/zju-learning-assistant/releases/tag/v0.3.2
操作系统：macos 13.6.3

**Comment by PeiPei233** [comment]
我也发现这个问题了 关键是我打包完传上来再下载回去就损坏了😇

**Comment by chkhu** [comment]
好嘞，x86可以正常使用，转译应该没什么影响，美美用上了

已star，等俺空下来好好学习一下🤩

<img width="1057" alt="image" src="https://github.com/PeiPei233/zju-learning-assistant/assets/109655311/6a75a10e-c1a9-42fc-88a5-d23a779a5763">

**Comment by PeiPei233** [comment]
试了一下是Mac自带的实用归档工具抽风了，建议下载 `.app.tar.gz` 之后用 `tar -zxvf zju-learning-assistant_aarch64.app.tar.gz` 获取 `.app` 文件之后自己拷贝到应用程序文件夹里
