### ISSUE TITLE
Mac ARM64下显示文件已损坏

### ISSUE THREAD

**Issue by Orwell-Yu** [PeiPei233/zju-learning-assistant#6]
<img width="300" alt="image" src="https://github.com/PeiPei233/zju-learning-assistant/assets/111028216/d7b23864-1bfa-4519-8fe0-e950cd64cddf">

对应Mac OS 版本14.3.1

对应软件版本0.3.2

下载内容为 zju-learning-assistant_0.3.2_aarch64.dmg

**Comment by PeiPei233** [comment]
之前有人提过这个问题啦 是Apple的实用归档工具抽风了 #4 
建议下载 `.app.tar.gz` 之后用 `tar -zxvf zju-learning-assistant_aarch64.app.tar.gz` 获取 `.app` 文件之后自己拷贝到应用程序文件夹里，嫌麻烦就直接用 x64 的包也行
